---
name: Ts-Shara No Break Status Api
version: dev
slug: ssh
description: An .Net 8 API for Ts-Shara No Break Status
url: https://github.com/dev-vinicius-andrade
codenotary: vinicius.andrade@codescovery.com
startup: services
ingress: true
ingress_port: 0
ingress_stream: true
ingress_entry: /swagger

init: false
panel_icon: mdi:api
panel_title: Ts-Shara No Break Status Api
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armv7
ports:
  80/tcp: 8245
  443/tcp: 8246
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
hassio_api: true
hassio_role: manager
services:
  - mysql:want
  - mqtt:want
homeassistant_api: true
host_network: true
uart: true
usb: true
gpio: true
audio: true
apparmor: false
host_dbus: true
docker_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/mem
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
journald: true
options:
  log_level: Information  
  serial_new_line_indicator: "\r"
  serial_read_timeout_milliseconds: 100
  serial_commands_get_device_information_command: "I\r"
  serial_commands_get_device_information_delay_milliseconds: 1000
  serial_commands_get_device_status_command: "Q1\r"
  serial_commands_get_device_status_delay_milliseconds: 1000
  serial_valid_prefixes:
    - "?TS SHARA"
    - "TS SHARA"
    - "S SHARA"
    - "#TS SHAR"
    - "V23T405"
    - "V23T406"
    - "V23T401"
    - "V23T402T"
    - "V23T402T"
    - "V23T404T"
    - "V22T405"
    - "V22T406"
    - "V22T401"
    - "V22T402T"
    - "V22T402T"
    - "V22T404T"
    - "V21T401"
    - "TS Shara"
    - "V13T425"
    - "V.014.00"
    - "V.015.00"
    - "TS Shara"
    - "V17T376"
    - "V17T375"
    - "V17T374"
    - "V17T373"
schema:
  log_level: list(Trace|Debug|Information|Warning|Error|Critical)?
  notifier_hours: int?
  notifier_minutes: int?
  notifier_seconds: int?
  notifier_milliseconds: int?
  notifier_endpoint: str?
  serial_new_line_indicator: str
  serial_read_timeout_days: int?
  serial_read_timeout_hours: int?
  serial_read_timeout_minutes: int?
  serial_read_timeout_seconds: int?
  serial_read_timeout_milliseconds: int?
  serial_commands_get_device_information_command: str
  serial_commands_get_device_information_delay_days: int?
  serial_commands_get_device_information_delay_hours: int?
  serial_commands_get_device_information_delay_minutes: int?
  serial_commands_get_device_information_delay_seconds: int?
  serial_commands_get_device_information_delay_milliseconds: int?
  serial_commands_get_device_status_command: str
  serial_commands_get_device_status_delay_days: int?
  serial_commands_get_device_status_delay_hours: int?
  serial_commands_get_device_status_delay_minutes: int?
  serial_commands_get_device_status_delay_seconds: int?
  serial_commands_get_device_status_delay_milliseconds: int?
  serial_valid_prefixes:
  - str