name: Docker Build and Push

on:
  push:
    branches:
      - 'master'
      - 'development'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    env:
      DOCKER_REPOSITORY_NAME: 'home-assistant/ts-shara'
      DOCKER_REGISTRY: registry.codescovery.com
      DOCKER_USERNAME: ${{ secrets.CODESCOVERY_REGISTRY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.CODESCOVERY_REGISTRY_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
        tags: | 
          ${{ steps.meta.outputs.tags }}
    - name: push 
      if: github.event_name != 'pull_request' 
      run: |
        docker image ls

# ${{ steps.meta.outputs.tags }}
         