name: .Net Publish Package

on:
  push:
    branches:
      - 'master'
      - 'development'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    env:
      DOCKER_REPOSITORY_NAME: 'codescovery/home-assistant/ts-shara'
      DOCKER_REGISTRY: registry.codescovery.com
      DOCKER_USERNAME: ${{ secrets.CODESCOVERY_REGISTRY_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.CODESCOVERY_REGISTRY_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{env.DOCKER_REPOSITORY_NAME}}
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        registry: $Env:DOCKER_REGISTRY
        username: $Env:DOCKER_USERNAME
        password: $Env:DOCKER_PASSWORD
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ../../
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
         $env:DOCKER $env:BUILD_VERSION
         $env:LATEST_TAG